name: "nix flake check"
on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Flake metadata
      run: |
        nix flake metadata
        nix flake show

    - name: Flake check
      run: |
        nix flake check -L

    - name: Run logwatch
      run: |
        nix run . -- --version

    - name: Formatter check
      run: |
        nix fmt
        git diff --exit-code
